# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adil/tntcxx-router

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adil/tntcxx-router

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adil/tntcxx-router/CMakeFiles /home/adil/tntcxx-router//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adil/tntcxx-router/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ev

# Build rule for target.
ev: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ev
.PHONY : ev

# fast build rule for target.
ev/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ev.dir/build.make CMakeFiles/ev.dir/build
.PHONY : ev/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named MempoolUnit.test

# Build rule for target.
MempoolUnit.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MempoolUnit.test
.PHONY : MempoolUnit.test

# fast build rule for target.
MempoolUnit.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MempoolUnit.test.dir/build.make CMakeFiles/MempoolUnit.test.dir/build
.PHONY : MempoolUnit.test/fast

#=============================================================================
# Target rules for targets named CStrUnit.test

# Build rule for target.
CStrUnit.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CStrUnit.test
.PHONY : CStrUnit.test

# fast build rule for target.
CStrUnit.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CStrUnit.test.dir/build.make CMakeFiles/CStrUnit.test.dir/build
.PHONY : CStrUnit.test/fast

#=============================================================================
# Target rules for targets named CommonUnit.test

# Build rule for target.
CommonUnit.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CommonUnit.test
.PHONY : CommonUnit.test

# fast build rule for target.
CommonUnit.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CommonUnit.test.dir/build.make CMakeFiles/CommonUnit.test.dir/build
.PHONY : CommonUnit.test/fast

#=============================================================================
# Target rules for targets named TraitsUnit.test

# Build rule for target.
TraitsUnit.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TraitsUnit.test
.PHONY : TraitsUnit.test

# fast build rule for target.
TraitsUnit.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TraitsUnit.test.dir/build.make CMakeFiles/TraitsUnit.test.dir/build
.PHONY : TraitsUnit.test/fast

#=============================================================================
# Target rules for targets named RefVectorUnit.test

# Build rule for target.
RefVectorUnit.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RefVectorUnit.test
.PHONY : RefVectorUnit.test

# fast build rule for target.
RefVectorUnit.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RefVectorUnit.test.dir/build.make CMakeFiles/RefVectorUnit.test.dir/build
.PHONY : RefVectorUnit.test/fast

#=============================================================================
# Target rules for targets named Base64Unit.test

# Build rule for target.
Base64Unit.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Base64Unit.test
.PHONY : Base64Unit.test

# fast build rule for target.
Base64Unit.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base64Unit.test.dir/build.make CMakeFiles/Base64Unit.test.dir/build
.PHONY : Base64Unit.test/fast

#=============================================================================
# Target rules for targets named BufferUnit.test

# Build rule for target.
BufferUnit.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BufferUnit.test
.PHONY : BufferUnit.test

# fast build rule for target.
BufferUnit.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BufferUnit.test.dir/build.make CMakeFiles/BufferUnit.test.dir/build
.PHONY : BufferUnit.test/fast

#=============================================================================
# Target rules for targets named RingUnit.test

# Build rule for target.
RingUnit.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RingUnit.test
.PHONY : RingUnit.test

# fast build rule for target.
RingUnit.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RingUnit.test.dir/build.make CMakeFiles/RingUnit.test.dir/build
.PHONY : RingUnit.test/fast

#=============================================================================
# Target rules for targets named ListUnit.test

# Build rule for target.
ListUnit.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ListUnit.test
.PHONY : ListUnit.test

# fast build rule for target.
ListUnit.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ListUnit.test.dir/build.make CMakeFiles/ListUnit.test.dir/build
.PHONY : ListUnit.test/fast

#=============================================================================
# Target rules for targets named RulesUnit.test

# Build rule for target.
RulesUnit.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RulesUnit.test
.PHONY : RulesUnit.test

# fast build rule for target.
RulesUnit.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RulesUnit.test.dir/build.make CMakeFiles/RulesUnit.test.dir/build
.PHONY : RulesUnit.test/fast

#=============================================================================
# Target rules for targets named EncDecUnit.test

# Build rule for target.
EncDecUnit.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EncDecUnit.test
.PHONY : EncDecUnit.test

# fast build rule for target.
EncDecUnit.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncDecUnit.test.dir/build.make CMakeFiles/EncDecUnit.test.dir/build
.PHONY : EncDecUnit.test/fast

#=============================================================================
# Target rules for targets named Client.test

# Build rule for target.
Client.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Client.test
.PHONY : Client.test

# fast build rule for target.
Client.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.test.dir/build.make CMakeFiles/Client.test.dir/build
.PHONY : Client.test/fast

#=============================================================================
# Target rules for targets named BufferPerf.test

# Build rule for target.
BufferPerf.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BufferPerf.test
.PHONY : BufferPerf.test

# fast build rule for target.
BufferPerf.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BufferPerf.test.dir/build.make CMakeFiles/BufferPerf.test.dir/build
.PHONY : BufferPerf.test/fast

#=============================================================================
# Target rules for targets named ClientPerf.test

# Build rule for target.
ClientPerf.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ClientPerf.test
.PHONY : ClientPerf.test

# fast build rule for target.
ClientPerf.test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientPerf.test.dir/build.make CMakeFiles/ClientPerf.test.dir/build
.PHONY : ClientPerf.test/fast

#=============================================================================
# Target rules for targets named SimpleExample

# Build rule for target.
SimpleExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleExample
.PHONY : SimpleExample

# fast build rule for target.
SimpleExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleExample.dir/build.make CMakeFiles/SimpleExample.dir/build
.PHONY : SimpleExample/fast

#=============================================================================
# Target rules for targets named SqlExample

# Build rule for target.
SqlExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SqlExample
.PHONY : SqlExample

# fast build rule for target.
SqlExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SqlExample.dir/build.make CMakeFiles/SqlExample.dir/build
.PHONY : SqlExample/fast

#=============================================================================
# Target rules for targets named SchemalessExample

# Build rule for target.
SchemalessExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SchemalessExample
.PHONY : SchemalessExample

# fast build rule for target.
SchemalessExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SchemalessExample.dir/build.make CMakeFiles/SchemalessExample.dir/build
.PHONY : SchemalessExample/fast

#=============================================================================
# Target rules for targets named LinkTest

# Build rule for target.
LinkTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LinkTest
.PHONY : LinkTest

# fast build rule for target.
LinkTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkTest.dir/build.make CMakeFiles/LinkTest.dir/build
.PHONY : LinkTest/fast

#=============================================================================
# Target rules for targets named msgpuck

# Build rule for target.
msgpuck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 msgpuck
.PHONY : msgpuck

# fast build rule for target.
msgpuck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/msgpuck-build/CMakeFiles/msgpuck.dir/build.make _deps/msgpuck-build/CMakeFiles/msgpuck.dir/build
.PHONY : msgpuck/fast

examples/Schemaless.o: examples/Schemaless.cpp.o
.PHONY : examples/Schemaless.o

# target to build an object file
examples/Schemaless.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SchemalessExample.dir/build.make CMakeFiles/SchemalessExample.dir/examples/Schemaless.cpp.o
.PHONY : examples/Schemaless.cpp.o

examples/Schemaless.i: examples/Schemaless.cpp.i
.PHONY : examples/Schemaless.i

# target to preprocess a source file
examples/Schemaless.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SchemalessExample.dir/build.make CMakeFiles/SchemalessExample.dir/examples/Schemaless.cpp.i
.PHONY : examples/Schemaless.cpp.i

examples/Schemaless.s: examples/Schemaless.cpp.s
.PHONY : examples/Schemaless.s

# target to generate assembly for a file
examples/Schemaless.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SchemalessExample.dir/build.make CMakeFiles/SchemalessExample.dir/examples/Schemaless.cpp.s
.PHONY : examples/Schemaless.cpp.s

examples/Simple.o: examples/Simple.cpp.o
.PHONY : examples/Simple.o

# target to build an object file
examples/Simple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleExample.dir/build.make CMakeFiles/SimpleExample.dir/examples/Simple.cpp.o
.PHONY : examples/Simple.cpp.o

examples/Simple.i: examples/Simple.cpp.i
.PHONY : examples/Simple.i

# target to preprocess a source file
examples/Simple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleExample.dir/build.make CMakeFiles/SimpleExample.dir/examples/Simple.cpp.i
.PHONY : examples/Simple.cpp.i

examples/Simple.s: examples/Simple.cpp.s
.PHONY : examples/Simple.s

# target to generate assembly for a file
examples/Simple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleExample.dir/build.make CMakeFiles/SimpleExample.dir/examples/Simple.cpp.s
.PHONY : examples/Simple.cpp.s

examples/Sql.o: examples/Sql.cpp.o
.PHONY : examples/Sql.o

# target to build an object file
examples/Sql.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SqlExample.dir/build.make CMakeFiles/SqlExample.dir/examples/Sql.cpp.o
.PHONY : examples/Sql.cpp.o

examples/Sql.i: examples/Sql.cpp.i
.PHONY : examples/Sql.i

# target to preprocess a source file
examples/Sql.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SqlExample.dir/build.make CMakeFiles/SqlExample.dir/examples/Sql.cpp.i
.PHONY : examples/Sql.cpp.i

examples/Sql.s: examples/Sql.cpp.s
.PHONY : examples/Sql.s

# target to generate assembly for a file
examples/Sql.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SqlExample.dir/build.make CMakeFiles/SqlExample.dir/examples/Sql.cpp.s
.PHONY : examples/Sql.cpp.s

test/Base64UnitTest.o: test/Base64UnitTest.cpp.o
.PHONY : test/Base64UnitTest.o

# target to build an object file
test/Base64UnitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base64Unit.test.dir/build.make CMakeFiles/Base64Unit.test.dir/test/Base64UnitTest.cpp.o
.PHONY : test/Base64UnitTest.cpp.o

test/Base64UnitTest.i: test/Base64UnitTest.cpp.i
.PHONY : test/Base64UnitTest.i

# target to preprocess a source file
test/Base64UnitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base64Unit.test.dir/build.make CMakeFiles/Base64Unit.test.dir/test/Base64UnitTest.cpp.i
.PHONY : test/Base64UnitTest.cpp.i

test/Base64UnitTest.s: test/Base64UnitTest.cpp.s
.PHONY : test/Base64UnitTest.s

# target to generate assembly for a file
test/Base64UnitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base64Unit.test.dir/build.make CMakeFiles/Base64Unit.test.dir/test/Base64UnitTest.cpp.s
.PHONY : test/Base64UnitTest.cpp.s

test/BufferPerfTest.o: test/BufferPerfTest.cpp.o
.PHONY : test/BufferPerfTest.o

# target to build an object file
test/BufferPerfTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BufferPerf.test.dir/build.make CMakeFiles/BufferPerf.test.dir/test/BufferPerfTest.cpp.o
.PHONY : test/BufferPerfTest.cpp.o

test/BufferPerfTest.i: test/BufferPerfTest.cpp.i
.PHONY : test/BufferPerfTest.i

# target to preprocess a source file
test/BufferPerfTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BufferPerf.test.dir/build.make CMakeFiles/BufferPerf.test.dir/test/BufferPerfTest.cpp.i
.PHONY : test/BufferPerfTest.cpp.i

test/BufferPerfTest.s: test/BufferPerfTest.cpp.s
.PHONY : test/BufferPerfTest.s

# target to generate assembly for a file
test/BufferPerfTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BufferPerf.test.dir/build.make CMakeFiles/BufferPerf.test.dir/test/BufferPerfTest.cpp.s
.PHONY : test/BufferPerfTest.cpp.s

test/BufferUnitTest.o: test/BufferUnitTest.cpp.o
.PHONY : test/BufferUnitTest.o

# target to build an object file
test/BufferUnitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BufferUnit.test.dir/build.make CMakeFiles/BufferUnit.test.dir/test/BufferUnitTest.cpp.o
.PHONY : test/BufferUnitTest.cpp.o

test/BufferUnitTest.i: test/BufferUnitTest.cpp.i
.PHONY : test/BufferUnitTest.i

# target to preprocess a source file
test/BufferUnitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BufferUnit.test.dir/build.make CMakeFiles/BufferUnit.test.dir/test/BufferUnitTest.cpp.i
.PHONY : test/BufferUnitTest.cpp.i

test/BufferUnitTest.s: test/BufferUnitTest.cpp.s
.PHONY : test/BufferUnitTest.s

# target to generate assembly for a file
test/BufferUnitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BufferUnit.test.dir/build.make CMakeFiles/BufferUnit.test.dir/test/BufferUnitTest.cpp.s
.PHONY : test/BufferUnitTest.cpp.s

test/CStrUnitTest.o: test/CStrUnitTest.cpp.o
.PHONY : test/CStrUnitTest.o

# target to build an object file
test/CStrUnitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CStrUnit.test.dir/build.make CMakeFiles/CStrUnit.test.dir/test/CStrUnitTest.cpp.o
.PHONY : test/CStrUnitTest.cpp.o

test/CStrUnitTest.i: test/CStrUnitTest.cpp.i
.PHONY : test/CStrUnitTest.i

# target to preprocess a source file
test/CStrUnitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CStrUnit.test.dir/build.make CMakeFiles/CStrUnit.test.dir/test/CStrUnitTest.cpp.i
.PHONY : test/CStrUnitTest.cpp.i

test/CStrUnitTest.s: test/CStrUnitTest.cpp.s
.PHONY : test/CStrUnitTest.s

# target to generate assembly for a file
test/CStrUnitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CStrUnit.test.dir/build.make CMakeFiles/CStrUnit.test.dir/test/CStrUnitTest.cpp.s
.PHONY : test/CStrUnitTest.cpp.s

test/ClientPerfTest.o: test/ClientPerfTest.cpp.o
.PHONY : test/ClientPerfTest.o

# target to build an object file
test/ClientPerfTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientPerf.test.dir/build.make CMakeFiles/ClientPerf.test.dir/test/ClientPerfTest.cpp.o
.PHONY : test/ClientPerfTest.cpp.o

test/ClientPerfTest.i: test/ClientPerfTest.cpp.i
.PHONY : test/ClientPerfTest.i

# target to preprocess a source file
test/ClientPerfTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientPerf.test.dir/build.make CMakeFiles/ClientPerf.test.dir/test/ClientPerfTest.cpp.i
.PHONY : test/ClientPerfTest.cpp.i

test/ClientPerfTest.s: test/ClientPerfTest.cpp.s
.PHONY : test/ClientPerfTest.s

# target to generate assembly for a file
test/ClientPerfTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClientPerf.test.dir/build.make CMakeFiles/ClientPerf.test.dir/test/ClientPerfTest.cpp.s
.PHONY : test/ClientPerfTest.cpp.s

test/ClientTest.o: test/ClientTest.cpp.o
.PHONY : test/ClientTest.o

# target to build an object file
test/ClientTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.test.dir/build.make CMakeFiles/Client.test.dir/test/ClientTest.cpp.o
.PHONY : test/ClientTest.cpp.o

test/ClientTest.i: test/ClientTest.cpp.i
.PHONY : test/ClientTest.i

# target to preprocess a source file
test/ClientTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.test.dir/build.make CMakeFiles/Client.test.dir/test/ClientTest.cpp.i
.PHONY : test/ClientTest.cpp.i

test/ClientTest.s: test/ClientTest.cpp.s
.PHONY : test/ClientTest.s

# target to generate assembly for a file
test/ClientTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.test.dir/build.make CMakeFiles/Client.test.dir/test/ClientTest.cpp.s
.PHONY : test/ClientTest.cpp.s

test/CommonUnitTest.o: test/CommonUnitTest.cpp.o
.PHONY : test/CommonUnitTest.o

# target to build an object file
test/CommonUnitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CommonUnit.test.dir/build.make CMakeFiles/CommonUnit.test.dir/test/CommonUnitTest.cpp.o
.PHONY : test/CommonUnitTest.cpp.o

test/CommonUnitTest.i: test/CommonUnitTest.cpp.i
.PHONY : test/CommonUnitTest.i

# target to preprocess a source file
test/CommonUnitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CommonUnit.test.dir/build.make CMakeFiles/CommonUnit.test.dir/test/CommonUnitTest.cpp.i
.PHONY : test/CommonUnitTest.cpp.i

test/CommonUnitTest.s: test/CommonUnitTest.cpp.s
.PHONY : test/CommonUnitTest.s

# target to generate assembly for a file
test/CommonUnitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CommonUnit.test.dir/build.make CMakeFiles/CommonUnit.test.dir/test/CommonUnitTest.cpp.s
.PHONY : test/CommonUnitTest.cpp.s

test/EncDecTest.o: test/EncDecTest.cpp.o
.PHONY : test/EncDecTest.o

# target to build an object file
test/EncDecTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncDecUnit.test.dir/build.make CMakeFiles/EncDecUnit.test.dir/test/EncDecTest.cpp.o
.PHONY : test/EncDecTest.cpp.o

test/EncDecTest.i: test/EncDecTest.cpp.i
.PHONY : test/EncDecTest.i

# target to preprocess a source file
test/EncDecTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncDecUnit.test.dir/build.make CMakeFiles/EncDecUnit.test.dir/test/EncDecTest.cpp.i
.PHONY : test/EncDecTest.cpp.i

test/EncDecTest.s: test/EncDecTest.cpp.s
.PHONY : test/EncDecTest.s

# target to generate assembly for a file
test/EncDecTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncDecUnit.test.dir/build.make CMakeFiles/EncDecUnit.test.dir/test/EncDecTest.cpp.s
.PHONY : test/EncDecTest.cpp.s

test/LinkTest/Main.o: test/LinkTest/Main.cpp.o
.PHONY : test/LinkTest/Main.o

# target to build an object file
test/LinkTest/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkTest.dir/build.make CMakeFiles/LinkTest.dir/test/LinkTest/Main.cpp.o
.PHONY : test/LinkTest/Main.cpp.o

test/LinkTest/Main.i: test/LinkTest/Main.cpp.i
.PHONY : test/LinkTest/Main.i

# target to preprocess a source file
test/LinkTest/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkTest.dir/build.make CMakeFiles/LinkTest.dir/test/LinkTest/Main.cpp.i
.PHONY : test/LinkTest/Main.cpp.i

test/LinkTest/Main.s: test/LinkTest/Main.cpp.s
.PHONY : test/LinkTest/Main.s

# target to generate assembly for a file
test/LinkTest/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkTest.dir/build.make CMakeFiles/LinkTest.dir/test/LinkTest/Main.cpp.s
.PHONY : test/LinkTest/Main.cpp.s

test/LinkTest/Secondary.o: test/LinkTest/Secondary.cpp.o
.PHONY : test/LinkTest/Secondary.o

# target to build an object file
test/LinkTest/Secondary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkTest.dir/build.make CMakeFiles/LinkTest.dir/test/LinkTest/Secondary.cpp.o
.PHONY : test/LinkTest/Secondary.cpp.o

test/LinkTest/Secondary.i: test/LinkTest/Secondary.cpp.i
.PHONY : test/LinkTest/Secondary.i

# target to preprocess a source file
test/LinkTest/Secondary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkTest.dir/build.make CMakeFiles/LinkTest.dir/test/LinkTest/Secondary.cpp.i
.PHONY : test/LinkTest/Secondary.cpp.i

test/LinkTest/Secondary.s: test/LinkTest/Secondary.cpp.s
.PHONY : test/LinkTest/Secondary.s

# target to generate assembly for a file
test/LinkTest/Secondary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LinkTest.dir/build.make CMakeFiles/LinkTest.dir/test/LinkTest/Secondary.cpp.s
.PHONY : test/LinkTest/Secondary.cpp.s

test/ListUnitTest.o: test/ListUnitTest.cpp.o
.PHONY : test/ListUnitTest.o

# target to build an object file
test/ListUnitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ListUnit.test.dir/build.make CMakeFiles/ListUnit.test.dir/test/ListUnitTest.cpp.o
.PHONY : test/ListUnitTest.cpp.o

test/ListUnitTest.i: test/ListUnitTest.cpp.i
.PHONY : test/ListUnitTest.i

# target to preprocess a source file
test/ListUnitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ListUnit.test.dir/build.make CMakeFiles/ListUnit.test.dir/test/ListUnitTest.cpp.i
.PHONY : test/ListUnitTest.cpp.i

test/ListUnitTest.s: test/ListUnitTest.cpp.s
.PHONY : test/ListUnitTest.s

# target to generate assembly for a file
test/ListUnitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ListUnit.test.dir/build.make CMakeFiles/ListUnit.test.dir/test/ListUnitTest.cpp.s
.PHONY : test/ListUnitTest.cpp.s

test/MempoolUnitTest.o: test/MempoolUnitTest.cpp.o
.PHONY : test/MempoolUnitTest.o

# target to build an object file
test/MempoolUnitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MempoolUnit.test.dir/build.make CMakeFiles/MempoolUnit.test.dir/test/MempoolUnitTest.cpp.o
.PHONY : test/MempoolUnitTest.cpp.o

test/MempoolUnitTest.i: test/MempoolUnitTest.cpp.i
.PHONY : test/MempoolUnitTest.i

# target to preprocess a source file
test/MempoolUnitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MempoolUnit.test.dir/build.make CMakeFiles/MempoolUnit.test.dir/test/MempoolUnitTest.cpp.i
.PHONY : test/MempoolUnitTest.cpp.i

test/MempoolUnitTest.s: test/MempoolUnitTest.cpp.s
.PHONY : test/MempoolUnitTest.s

# target to generate assembly for a file
test/MempoolUnitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MempoolUnit.test.dir/build.make CMakeFiles/MempoolUnit.test.dir/test/MempoolUnitTest.cpp.s
.PHONY : test/MempoolUnitTest.cpp.s

test/RefVectorUnitTest.o: test/RefVectorUnitTest.cpp.o
.PHONY : test/RefVectorUnitTest.o

# target to build an object file
test/RefVectorUnitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RefVectorUnit.test.dir/build.make CMakeFiles/RefVectorUnit.test.dir/test/RefVectorUnitTest.cpp.o
.PHONY : test/RefVectorUnitTest.cpp.o

test/RefVectorUnitTest.i: test/RefVectorUnitTest.cpp.i
.PHONY : test/RefVectorUnitTest.i

# target to preprocess a source file
test/RefVectorUnitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RefVectorUnit.test.dir/build.make CMakeFiles/RefVectorUnit.test.dir/test/RefVectorUnitTest.cpp.i
.PHONY : test/RefVectorUnitTest.cpp.i

test/RefVectorUnitTest.s: test/RefVectorUnitTest.cpp.s
.PHONY : test/RefVectorUnitTest.s

# target to generate assembly for a file
test/RefVectorUnitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RefVectorUnit.test.dir/build.make CMakeFiles/RefVectorUnit.test.dir/test/RefVectorUnitTest.cpp.s
.PHONY : test/RefVectorUnitTest.cpp.s

test/RingUnitTest.o: test/RingUnitTest.cpp.o
.PHONY : test/RingUnitTest.o

# target to build an object file
test/RingUnitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RingUnit.test.dir/build.make CMakeFiles/RingUnit.test.dir/test/RingUnitTest.cpp.o
.PHONY : test/RingUnitTest.cpp.o

test/RingUnitTest.i: test/RingUnitTest.cpp.i
.PHONY : test/RingUnitTest.i

# target to preprocess a source file
test/RingUnitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RingUnit.test.dir/build.make CMakeFiles/RingUnit.test.dir/test/RingUnitTest.cpp.i
.PHONY : test/RingUnitTest.cpp.i

test/RingUnitTest.s: test/RingUnitTest.cpp.s
.PHONY : test/RingUnitTest.s

# target to generate assembly for a file
test/RingUnitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RingUnit.test.dir/build.make CMakeFiles/RingUnit.test.dir/test/RingUnitTest.cpp.s
.PHONY : test/RingUnitTest.cpp.s

test/RulesUnitTest.o: test/RulesUnitTest.cpp.o
.PHONY : test/RulesUnitTest.o

# target to build an object file
test/RulesUnitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RulesUnit.test.dir/build.make CMakeFiles/RulesUnit.test.dir/test/RulesUnitTest.cpp.o
.PHONY : test/RulesUnitTest.cpp.o

test/RulesUnitTest.i: test/RulesUnitTest.cpp.i
.PHONY : test/RulesUnitTest.i

# target to preprocess a source file
test/RulesUnitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RulesUnit.test.dir/build.make CMakeFiles/RulesUnit.test.dir/test/RulesUnitTest.cpp.i
.PHONY : test/RulesUnitTest.cpp.i

test/RulesUnitTest.s: test/RulesUnitTest.cpp.s
.PHONY : test/RulesUnitTest.s

# target to generate assembly for a file
test/RulesUnitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RulesUnit.test.dir/build.make CMakeFiles/RulesUnit.test.dir/test/RulesUnitTest.cpp.s
.PHONY : test/RulesUnitTest.cpp.s

test/TraitsUnitTest.o: test/TraitsUnitTest.cpp.o
.PHONY : test/TraitsUnitTest.o

# target to build an object file
test/TraitsUnitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TraitsUnit.test.dir/build.make CMakeFiles/TraitsUnit.test.dir/test/TraitsUnitTest.cpp.o
.PHONY : test/TraitsUnitTest.cpp.o

test/TraitsUnitTest.i: test/TraitsUnitTest.cpp.i
.PHONY : test/TraitsUnitTest.i

# target to preprocess a source file
test/TraitsUnitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TraitsUnit.test.dir/build.make CMakeFiles/TraitsUnit.test.dir/test/TraitsUnitTest.cpp.i
.PHONY : test/TraitsUnitTest.cpp.i

test/TraitsUnitTest.s: test/TraitsUnitTest.cpp.s
.PHONY : test/TraitsUnitTest.s

# target to generate assembly for a file
test/TraitsUnitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TraitsUnit.test.dir/build.make CMakeFiles/TraitsUnit.test.dir/test/TraitsUnitTest.cpp.s
.PHONY : test/TraitsUnitTest.cpp.s

third_party/libev/ev.o: third_party/libev/ev.c.o
.PHONY : third_party/libev/ev.o

# target to build an object file
third_party/libev/ev.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ev.dir/build.make CMakeFiles/ev.dir/third_party/libev/ev.c.o
.PHONY : third_party/libev/ev.c.o

third_party/libev/ev.i: third_party/libev/ev.c.i
.PHONY : third_party/libev/ev.i

# target to preprocess a source file
third_party/libev/ev.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ev.dir/build.make CMakeFiles/ev.dir/third_party/libev/ev.c.i
.PHONY : third_party/libev/ev.c.i

third_party/libev/ev.s: third_party/libev/ev.c.s
.PHONY : third_party/libev/ev.s

# target to generate assembly for a file
third_party/libev/ev.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ev.dir/build.make CMakeFiles/ev.dir/third_party/libev/ev.c.s
.PHONY : third_party/libev/ev.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... Base64Unit.test"
	@echo "... BufferPerf.test"
	@echo "... BufferUnit.test"
	@echo "... CStrUnit.test"
	@echo "... Client.test"
	@echo "... ClientPerf.test"
	@echo "... CommonUnit.test"
	@echo "... EncDecUnit.test"
	@echo "... LinkTest"
	@echo "... ListUnit.test"
	@echo "... MempoolUnit.test"
	@echo "... RefVectorUnit.test"
	@echo "... RingUnit.test"
	@echo "... RulesUnit.test"
	@echo "... SchemalessExample"
	@echo "... SimpleExample"
	@echo "... SqlExample"
	@echo "... TraitsUnit.test"
	@echo "... ev"
	@echo "... msgpuck"
	@echo "... examples/Schemaless.o"
	@echo "... examples/Schemaless.i"
	@echo "... examples/Schemaless.s"
	@echo "... examples/Simple.o"
	@echo "... examples/Simple.i"
	@echo "... examples/Simple.s"
	@echo "... examples/Sql.o"
	@echo "... examples/Sql.i"
	@echo "... examples/Sql.s"
	@echo "... test/Base64UnitTest.o"
	@echo "... test/Base64UnitTest.i"
	@echo "... test/Base64UnitTest.s"
	@echo "... test/BufferPerfTest.o"
	@echo "... test/BufferPerfTest.i"
	@echo "... test/BufferPerfTest.s"
	@echo "... test/BufferUnitTest.o"
	@echo "... test/BufferUnitTest.i"
	@echo "... test/BufferUnitTest.s"
	@echo "... test/CStrUnitTest.o"
	@echo "... test/CStrUnitTest.i"
	@echo "... test/CStrUnitTest.s"
	@echo "... test/ClientPerfTest.o"
	@echo "... test/ClientPerfTest.i"
	@echo "... test/ClientPerfTest.s"
	@echo "... test/ClientTest.o"
	@echo "... test/ClientTest.i"
	@echo "... test/ClientTest.s"
	@echo "... test/CommonUnitTest.o"
	@echo "... test/CommonUnitTest.i"
	@echo "... test/CommonUnitTest.s"
	@echo "... test/EncDecTest.o"
	@echo "... test/EncDecTest.i"
	@echo "... test/EncDecTest.s"
	@echo "... test/LinkTest/Main.o"
	@echo "... test/LinkTest/Main.i"
	@echo "... test/LinkTest/Main.s"
	@echo "... test/LinkTest/Secondary.o"
	@echo "... test/LinkTest/Secondary.i"
	@echo "... test/LinkTest/Secondary.s"
	@echo "... test/ListUnitTest.o"
	@echo "... test/ListUnitTest.i"
	@echo "... test/ListUnitTest.s"
	@echo "... test/MempoolUnitTest.o"
	@echo "... test/MempoolUnitTest.i"
	@echo "... test/MempoolUnitTest.s"
	@echo "... test/RefVectorUnitTest.o"
	@echo "... test/RefVectorUnitTest.i"
	@echo "... test/RefVectorUnitTest.s"
	@echo "... test/RingUnitTest.o"
	@echo "... test/RingUnitTest.i"
	@echo "... test/RingUnitTest.s"
	@echo "... test/RulesUnitTest.o"
	@echo "... test/RulesUnitTest.i"
	@echo "... test/RulesUnitTest.s"
	@echo "... test/TraitsUnitTest.o"
	@echo "... test/TraitsUnitTest.i"
	@echo "... test/TraitsUnitTest.s"
	@echo "... third_party/libev/ev.o"
	@echo "... third_party/libev/ev.i"
	@echo "... third_party/libev/ev.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

